### ISSUE TITLE
Key title

### ISSUE THREAD

**Issue by t-pollington** [sigbertklinke/plot.matrix#4]
Dear @sigbertklinke 

I had a read of your vignette and documentation but couldn't find a way to give the key a heading. Is this functionality currently possible and if not then is `text()` the usual workaround for this?

Thanks, Tim.

**Comment by sigbertklinke** [comment]
Hi Tim,

currently it is not possible to give a heading to the key. Thus, you have to use` text()`.

Best Sigbert

**Comment by t-pollington** [comment]
Oakie dokie, thanks for confirming. On 30 Sep 2020 4:11 p.m., Sigbert Klinke <notifications@github.com> wrote:
Hi Tim,
currently it is not possible to give a heading to the key. Thus, you have to use text.
Best Sigbert
